[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-06/=lib/openzeppelin-contracts-06/",
    "lib-src/=lib/forge-std/src/",
    "utils/=lib/silo-foundry-utils/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
